### ISSUE TITLE
How to use it more correctly with Bootstrap Alert?

### ISSUE THREAD

**Issue by kukrik** [qcubed/bootstrap#2]
@spekary, There are no problems with using Bootstrap Modal, because modal is independent and displays the center of the screen as needed...

I have a second problem displaying a Bootstrap Alert when I use a second class with a template. I will explain a little bit. If I only use one page, for example, menu.php and menu.tpl.php. If I use Alert here and in a one place, it's okay. But I needed to bring menu.php into one class with a template. There's one button, if you click on it, the alert appears in the wrong place. 

The alert must be displayed in the menu.php specified location.

I will show a bit of my solution.
In menu.php =>
```php
require('MenuEditPanel.php');
.......
.......
       $this->pnlEditMenu = new MenuEditPanel($this);
       $this->pnlEditMenu->AutoRenderChildren = true;
......
......
// Alerts
        $this->lblMessage = new Bs\Alert($this);
        $this->lblMessage->setCssBoxValue("display", "none");
......
......
```
The question is how to target the alert in the right place? My thoughts are over. What are your suggestions or tips? Thanks in advance!

**Comment by spekary** [comment]
This is really a css and Bootstrap question. But as far as I can tell, its just a div. Create a container div, use css to put that container where you want, and draw the alert inside of that container.

**Comment by matthiaz** [comment]
I believe this is solved, so I'm closing the issue
